export COUNTRY_TOOLS_DB_USER=${COUNTRY_TOOLS_DB_USER}
export COUNTRY_TOOLS_DB_PASS=${COUNTRY_TOOLS_DB_PASS}
export COUNTRY_TOOLS_DB_HOST=${COUNTRY_TOOLS_DB_HOST}
export COUNTRY_TOOLS_DB_NAME=${COUNTRY_TOOLS_DB_NAME}
